name: MightyStick
main: MightyStick\Main
version: 1.0.0
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
author: RetiredDev
description: MightyStick
commands:
 mightystick:
  description: "Gives a stick"
